version: '2.0'
services:
  registry:
    image: registry:2.7
    ports:
      - 5000:5000
    volumes:
      - ./registry-data:/var/lib/registry
      - ./config.yml:/etc/docker/registry/config.yml
    restart: unless-stopped

  ui:
    image: joxit/docker-registry-ui:latest
    ports:
      - 8090:80
    environment:
      - REGISTRY_TITLE=Container Registry Local
      - REGISTRY_URL=http://localhost:5000
      - SINGLE_REGISTRY=true
    restart: unless-stopped
    depends_on:
      - registry